/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TissRouteImport } from './routes/tiss'
import { Route as TelefoniaRouteImport } from './routes/telefonia'
import { Route as RepasseRouteImport } from './routes/repasse'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProntuarioRouteImport } from './routes/prontuario'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as ProcedimentosRouteImport } from './routes/procedimentos'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FaturamentoRouteImport } from './routes/faturamento'
import { Route as EspecialidadesRouteImport } from './routes/especialidades'
import { Route as ConveniosRouteImport } from './routes/convenios'
import { Route as ConsultorioRouteImport } from './routes/consultorio'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceiroRelatoriosRouteImport } from './routes/financeiro/relatorios'
import { Route as FinanceiroFluxoCaixaRouteImport } from './routes/financeiro/fluxo-caixa'
import { Route as FinanceiroContasReceberRouteImport } from './routes/financeiro/contas-receber'
import { Route as FinanceiroContasPagarRouteImport } from './routes/financeiro/contas-pagar'
import { Route as FinanceiroComissoesRouteImport } from './routes/financeiro/comissoes'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TissRoute = TissRouteImport.update({
  id: '/tiss',
  path: '/tiss',
  getParentRoute: () => rootRouteImport,
} as any)
const TelefoniaRoute = TelefoniaRouteImport.update({
  id: '/telefonia',
  path: '/telefonia',
  getParentRoute: () => rootRouteImport,
} as any)
const RepasseRoute = RepasseRouteImport.update({
  id: '/repasse',
  path: '/repasse',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProntuarioRoute = ProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosRoute = ProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturamentoRoute = FaturamentoRouteImport.update({
  id: '/faturamento',
  path: '/faturamento',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialidadesRoute = EspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ConveniosRoute = ConveniosRouteImport.update({
  id: '/convenios',
  path: '/convenios',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorioRoute = ConsultorioRouteImport.update({
  id: '/consultorio',
  path: '/consultorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRelatoriosRoute = FinanceiroRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroFluxoCaixaRoute = FinanceiroFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroContasReceberRoute = FinanceiroContasReceberRouteImport.update({
  id: '/contas-receber',
  path: '/contas-receber',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroContasPagarRoute = FinanceiroContasPagarRouteImport.update({
  id: '/contas-pagar',
  path: '/contas-pagar',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroComissoesRoute = FinanceiroComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => FinanceiroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consultorio': typeof ConsultorioRoute
  '/convenios': typeof ConveniosRoute
  '/especialidades': typeof EspecialidadesRoute
  '/faturamento': typeof FaturamentoRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/profissionais': typeof ProfissionaisRoute
  '/prontuario': typeof ProntuarioRoute
  '/relatorios': typeof RelatoriosRoute
  '/repasse': typeof RepasseRoute
  '/telefonia': typeof TelefoniaRoute
  '/tiss': typeof TissRoute
  '/usuarios': typeof UsuariosRoute
  '/whatsapp': typeof WhatsappRoute
  '/financeiro/comissoes': typeof FinanceiroComissoesRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/fluxo-caixa': typeof FinanceiroFluxoCaixaRoute
  '/financeiro/relatorios': typeof FinanceiroRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consultorio': typeof ConsultorioRoute
  '/convenios': typeof ConveniosRoute
  '/especialidades': typeof EspecialidadesRoute
  '/faturamento': typeof FaturamentoRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/profissionais': typeof ProfissionaisRoute
  '/prontuario': typeof ProntuarioRoute
  '/relatorios': typeof RelatoriosRoute
  '/repasse': typeof RepasseRoute
  '/telefonia': typeof TelefoniaRoute
  '/tiss': typeof TissRoute
  '/usuarios': typeof UsuariosRoute
  '/whatsapp': typeof WhatsappRoute
  '/financeiro/comissoes': typeof FinanceiroComissoesRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/fluxo-caixa': typeof FinanceiroFluxoCaixaRoute
  '/financeiro/relatorios': typeof FinanceiroRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consultorio': typeof ConsultorioRoute
  '/convenios': typeof ConveniosRoute
  '/especialidades': typeof EspecialidadesRoute
  '/faturamento': typeof FaturamentoRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/profissionais': typeof ProfissionaisRoute
  '/prontuario': typeof ProntuarioRoute
  '/relatorios': typeof RelatoriosRoute
  '/repasse': typeof RepasseRoute
  '/telefonia': typeof TelefoniaRoute
  '/tiss': typeof TissRoute
  '/usuarios': typeof UsuariosRoute
  '/whatsapp': typeof WhatsappRoute
  '/financeiro/comissoes': typeof FinanceiroComissoesRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/fluxo-caixa': typeof FinanceiroFluxoCaixaRoute
  '/financeiro/relatorios': typeof FinanceiroRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/consultorio'
    | '/convenios'
    | '/especialidades'
    | '/faturamento'
    | '/financeiro'
    | '/login'
    | '/pacientes'
    | '/procedimentos'
    | '/profissionais'
    | '/prontuario'
    | '/relatorios'
    | '/repasse'
    | '/telefonia'
    | '/tiss'
    | '/usuarios'
    | '/whatsapp'
    | '/financeiro/comissoes'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/consultorio'
    | '/convenios'
    | '/especialidades'
    | '/faturamento'
    | '/financeiro'
    | '/login'
    | '/pacientes'
    | '/procedimentos'
    | '/profissionais'
    | '/prontuario'
    | '/relatorios'
    | '/repasse'
    | '/telefonia'
    | '/tiss'
    | '/usuarios'
    | '/whatsapp'
    | '/financeiro/comissoes'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/relatorios'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/consultorio'
    | '/convenios'
    | '/especialidades'
    | '/faturamento'
    | '/financeiro'
    | '/login'
    | '/pacientes'
    | '/procedimentos'
    | '/profissionais'
    | '/prontuario'
    | '/relatorios'
    | '/repasse'
    | '/telefonia'
    | '/tiss'
    | '/usuarios'
    | '/whatsapp'
    | '/financeiro/comissoes'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConsultorioRoute: typeof ConsultorioRoute
  ConveniosRoute: typeof ConveniosRoute
  EspecialidadesRoute: typeof EspecialidadesRoute
  FaturamentoRoute: typeof FaturamentoRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  LoginRoute: typeof LoginRoute
  PacientesRoute: typeof PacientesRoute
  ProcedimentosRoute: typeof ProcedimentosRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  ProntuarioRoute: typeof ProntuarioRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RepasseRoute: typeof RepasseRoute
  TelefoniaRoute: typeof TelefoniaRoute
  TissRoute: typeof TissRoute
  UsuariosRoute: typeof UsuariosRoute
  WhatsappRoute: typeof WhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiss': {
      id: '/tiss'
      path: '/tiss'
      fullPath: '/tiss'
      preLoaderRoute: typeof TissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telefonia': {
      id: '/telefonia'
      path: '/telefonia'
      fullPath: '/telefonia'
      preLoaderRoute: typeof TelefoniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repasse': {
      id: '/repasse'
      path: '/repasse'
      fullPath: '/repasse'
      preLoaderRoute: typeof RepasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prontuario': {
      id: '/prontuario'
      path: '/prontuario'
      fullPath: '/prontuario'
      preLoaderRoute: typeof ProntuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos': {
      id: '/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof ProcedimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturamento': {
      id: '/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof FaturamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialidades': {
      id: '/especialidades'
      path: '/especialidades'
      fullPath: '/especialidades'
      preLoaderRoute: typeof EspecialidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convenios': {
      id: '/convenios'
      path: '/convenios'
      fullPath: '/convenios'
      preLoaderRoute: typeof ConveniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultorio': {
      id: '/consultorio'
      path: '/consultorio'
      fullPath: '/consultorio'
      preLoaderRoute: typeof ConsultorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/relatorios': {
      id: '/financeiro/relatorios'
      path: '/relatorios'
      fullPath: '/financeiro/relatorios'
      preLoaderRoute: typeof FinanceiroRelatoriosRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/fluxo-caixa': {
      id: '/financeiro/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/financeiro/fluxo-caixa'
      preLoaderRoute: typeof FinanceiroFluxoCaixaRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/contas-receber': {
      id: '/financeiro/contas-receber'
      path: '/contas-receber'
      fullPath: '/financeiro/contas-receber'
      preLoaderRoute: typeof FinanceiroContasReceberRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/contas-pagar': {
      id: '/financeiro/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/financeiro/contas-pagar'
      preLoaderRoute: typeof FinanceiroContasPagarRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/comissoes': {
      id: '/financeiro/comissoes'
      path: '/comissoes'
      fullPath: '/financeiro/comissoes'
      preLoaderRoute: typeof FinanceiroComissoesRouteImport
      parentRoute: typeof FinanceiroRoute
    }
  }
}

interface FinanceiroRouteChildren {
  FinanceiroComissoesRoute: typeof FinanceiroComissoesRoute
  FinanceiroContasPagarRoute: typeof FinanceiroContasPagarRoute
  FinanceiroContasReceberRoute: typeof FinanceiroContasReceberRoute
  FinanceiroFluxoCaixaRoute: typeof FinanceiroFluxoCaixaRoute
  FinanceiroRelatoriosRoute: typeof FinanceiroRelatoriosRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroComissoesRoute: FinanceiroComissoesRoute,
  FinanceiroContasPagarRoute: FinanceiroContasPagarRoute,
  FinanceiroContasReceberRoute: FinanceiroContasReceberRoute,
  FinanceiroFluxoCaixaRoute: FinanceiroFluxoCaixaRoute,
  FinanceiroRelatoriosRoute: FinanceiroRelatoriosRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConsultorioRoute: ConsultorioRoute,
  ConveniosRoute: ConveniosRoute,
  EspecialidadesRoute: EspecialidadesRoute,
  FaturamentoRoute: FaturamentoRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  LoginRoute: LoginRoute,
  PacientesRoute: PacientesRoute,
  ProcedimentosRoute: ProcedimentosRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  ProntuarioRoute: ProntuarioRoute,
  RelatoriosRoute: RelatoriosRoute,
  RepasseRoute: RepasseRoute,
  TelefoniaRoute: TelefoniaRoute,
  TissRoute: TissRoute,
  UsuariosRoute: UsuariosRoute,
  WhatsappRoute: WhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
